#!/bin/sh -e

# This script starts the Node-RED app with the default configuration (no-license)

if [ -z "$PORT" ]; then PORT=60999; fi
export PORT

# Set the PATH to include the 7zz directory and the additional directories
export PATH="/snap/thermal-camera-diagnosis-app/x1/bin/:/snap/thermal-camera-diagnosis-app/x1/usr/lib/python3/dist-packages:/snap/thermal-camera-diagnosis-app/x1/config/python-code/:$PATH"


# Set the default NodeRED user directory
UNLICENSED_USERDIR=$SNAP_USER_DATA/unlicensed/config/node-red


# Set the default NodeRED settings file


# Wait until the directory and necessary files become available
while [ ! -d "$UNLICENSED_USERDIR" ]; do
    echo "[start-node-red] Waiting for director to become available..."
    sleep 1 
done

# Start Node-RED with the default configuration (no-license)
UNLICENSED_NODE_RED_SETTINGS=$UNLICENSED_USERDIR/settings.js

# Start the Node-RED app
echo "Starting Node-RED app. Port: $PORT. Settings: $UNLICENSED_NODE_RED_SETTINGS. UserDir: $UNLICENSED_USERDIR."


# Start the Node-RED app in the background with no output
$SNAP/bin/node $SNAP/lib/node_modules/.bin/node-red -s $UNLICENSED_NODE_RED_SETTINGS -u $UNLICENSED_USERDIR