name: thermal-camera-diagnosis-app
title: Thermal Camera Diagnosis App
base: core22
version: "0.0.1"
summary: Thermal Camera Diagnosis App as part of Evgeniy Petrov's Bachelor Thesis
description: |
    NodeRED App for testing, development and debugging purposes 

grade: stable
confinement: strict

architectures:
    - build-on: amd64
    - build-on: arm64

slots:
    secure-assets:
        interface: content
        content: secure-assets
        source: 
            read:
                - $SNAP/secure-assets/thermal-camera-diagnosis-app

    service-token:
        interface: content
        content: service-token
        source:
            write:
                - $SNAP_DATA/service-token/thermal-camera-diagnosis-app

    package-assets:
        interface: content
        content: package-assets
        source:
            read:
                - $SNAP/package-assets/thermal-camera-diagnosis-app

plugs:
    active-solution:
        interface: content
        content: solutions
        target: $SNAP_COMMON/solutions

    datalayer:
        interface: content
        content: datalayer
        target: $SNAP_DATA/.datalayer


hooks:
    connect-plug-active-solution:
        plugs: [active-solution]

    remove:
        plugs: [active-solution]

apps:

    7zip:
        command: bin/7zz
        slots:
            - package-assets

    node-red:
        command: bin/start-node-red
        daemon: simple
        restart-condition: on-failure
        restart-delay: 15s
        plugs:
            - audio-playback
            - bluez
            - bluetooth-control
            - camera
            - network-bind
            - network
            - network-observe
            - pulseaudio
            - serial-port
            - removable-media
            - active-solution
        slots:
            - package-assets

parts:
    node:
        after: [node-red]
        plugin: dump
        source:
            - to amd64: ./snap/local/packages/node-v16.18.0-linux-x64.tar.gz
            - to arm64: ./snap/local/packages/node-v16.18.0-linux-arm64.tar.gz

    node-red:
        plugin: nil
        override-build: | # Whatever steps needed to install node-red into the install folder, which gets incorporated into the snap
            # setup npm
            npm_args="--unsafe-perm --prefix $SNAPCRAFT_PART_INSTALL/lib --omit=dev --no-fund"

            # npm config set unsafe-perm true
            # npm cache verify

            npm $npm_args install node-red@3.1.0

            # install factory shipped node-red plugins
            npm $npm_args install node-red-debugger@1.1.1
            # npm $npm_args install nrlint@1.1.0
            # npx nrlint --init > $SNAPCRAFT_PART_INSTALL/lib/.nrlintrc.js
        
            # install factory shipped library nodes
            npm $npm_args install node-red-dashboard@3.6.0
            npm $npm_args install node-red-contrib-influxdb@0.6.1 
            npm $npm_args install node-red-contrib-ctrlx-automation@1.8.19
            npm $npm_args install node-red-contrib-fs-ops@1.6.0
            npm $npm_args install node-red-contrib-buffer-parser@3.2.2
            npm $npm_args install node-red-contrib-queue-gate@1.5.5
            npm $npm_args install node-red-node-base64@0.3.0
            npm $npm_args install node-red-contrib-flogger-coco@1.2.2
            npm $npm_args install node-red-contrib-cpu@0.0.4
            npm $npm_args install node-red-contrib-loop@1.0.1
            npm $npm_args install node-red-contrib-full-msg-json-schema-validation@1.1.0
            npm $npm_args install node-red-contrib-modbustcp@1.2.3
            npm $npm_args install node-red-contrib-python-function@0.0.5    
            npm $npm_args install node-red-contrib-image-output@0.6.4 

            # modify node_modules
            find $SNAPCRAFT_PART_INSTALL -type f -name '*.js.swp' -delete
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type d -name test -prune -exec rm -rf {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type d -name doc -prune -exec rm -rf {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type d -name example -prune -exec rm -rf {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type d -name sample -prune -exec rm -rf {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type d -iname benchmark* -prune -exec rm -rf {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type d -iname .nyc_output -prune -exec rm -rf {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type d -iname unpacked -prune -exec rm -rf {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type d -name man* -prune -exec rm -rf {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type d -name tst -prune -exec rm -rf {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type d -iname demo -prune -exec rm -rf {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type f -name bench.gnu -exec rm -f {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type f -name .npmignore -exec rm -f {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type f -name .travis.yml -exec rm -f {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type f -name .jshintrc -exec rm -f {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type f -iname README.md -exec rm -f {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type f -iname HISTORY.md -exec rm -f {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type f -iname CONTRIBUTING.md -exec rm -f {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type f -iname CHANGE*.md -exec rm -f {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type f -iname .gitmodules -exec rm -f {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type f -iname .gitattributes -exec rm -f {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type f -iname .gitignore -exec rm -f {} \;
            find $SNAPCRAFT_PART_INSTALL/lib/node_modules -type f -iname "*~" -exec rm -f {} \;

    exiftool:
        plugin: dump
        source:
            - to amd64: ./snap/local/packages/Image-ExifTool-12.92.tar.gz
            - to arm64: ./snap/local/packages/Image-ExifTool-12.92.tar.gz
        organize:
            "*": bin/
    7zip:
        plugin: dump
        source:
            - to amd64: ./snap/local/packages/7z2301-linux-x64.tar.xz
            - to arm64: ./snap/local/packages/7z2301-linux-arm64.tar.xz
        organize:
            "*": bin/

    python-dependencies:
        plugin: python
        python-packages: 
            - requests
            - numpy
            - matplotlib
            - pandas
            - Pillow
            - opencv-contrib-python 
        build-packages:
            - python3-dev
            - build-essential
            - libatlas-base-dev
            - libblas-dev
            - liblapack-dev
        stage-packages:
            - libatlas-base-dev
            - libgl1
            - libglvnd0
            - libglx0
            - libice6
            - libsm6


    dump-config:
        plugin: dump
        source: ./config
        organize:
            "*": config/

    dump-scripts:
        plugin: dump
        source: ./scripts
        organize:
            "*": bin/

    package-assets:
        plugin: dump
        source: ./package-assets
        organize:
            "*": package-assets/

    secure-assets:
        plugin: dump
        source: ./secure-assets
        organize:
            "*": secure-assets/
