#!/bin/sh -e

#Copies NodeRED Unlicensed configuration directory into the hidden directory
NODERED_UNLICENSED_DIR=$SNAP_USER_DATA/unlicensed/config/node-red

if [ ! -d "$NODERED_UNLICENSED_DIR" ]; then 
   echo "Creating directory at $NODERED_UNLICENSED_DIR"
   mkdir -p $NODERED_UNLICENSED_DIR
fi
cp $SNAP/config/node-red/settings.js $SNAP_USER_DATA/unlicensed/config/node-red/settings.js
cp $SNAP/config/node-red/flows.json $SNAP_USER_DATA/unlicensed/config/node-red/flows.json
